version: '3'
services:
########## ##########
  dev:
    container_name: great_expectations_dev
    image: ge-test:latest
    volumes:
      - ./project:/home/project
      - ./data:/home/data
      - ./developer:/home/developer
    ports:
      - "8888:8888"
    env_file:
      - ./config/server.env